[package]
name = "joule"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powercap = { version = "^0.3.2" }
procfs = { default-features = false, version = "^0.11" }
