name: Testing the library

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
      - run: rustup component add clippy
      - run: cargo clippy --tests -- -D warnings
      - run: cargo test

